const ITEMS: Record<number, { name: string; rarity: number }> = {
  1: { name: 'Biscoito Globo', rarity: 1 },
  2: { name: 'Kenner Branca', rarity: 6 },
  3: { name: 'Biscoito Trakinas', rarity: 1 },
  4: { name: 'Caixa de som', rarity: 3 },
  5: { name: 'AK-47', rarity: 2 },
  6: { name: 'Glock-18', rarity: 2 },
  7: { name: 'Coca-Cola', rarity: 1 },
  8: { name: 'Munição 762mm', rarity: 1 },
  9: { name: 'Munição 556mm', rarity: 1 },
  10: { name: 'Munição 9mm', rarity: 1 },
  11: { name: 'AR-15', rarity: 2 },
  12: { name: 'Mesa de plástico', rarity: 1 },
  13: { name: 'Mochila iFood', rarity: 1 },
  14: { name: 'Picareta', rarity: 1 },
  15: { name: 'Minério de Ouro', rarity: 3 },
  16: { name: 'Diamante', rarity: 4 },
  17: { name: 'Rubi', rarity: 4 },
  18: { name: 'Minério de Esmeralda', rarity: 4 },
  19: { name: 'Ametista', rarity: 4 },
  20: { name: 'Minério de Ferro', rarity: 2 },
  21: { name: 'Minério de Carvão', rarity: 1 },
  22: { name: 'Cristal', rarity: 3 },
  23: { name: 'Pizza', rarity: 1 },
  24: { name: 'Coxinha', rarity: 1 },
  25: { name: 'Fofura', rarity: 1 },
  26: { name: 'Salsichão', rarity: 1 },
  27: { name: 'Espetinho De Carne', rarity: 1 },
  28: { name: 'Espetinho De Frango', rarity: 1 },
  29: { name: 'Pastel', rarity: 1 },
  30: { name: 'Água', rarity: 1 },
  31: { name: 'Suco', rarity: 1 },
  32: { name: 'Guaravita', rarity: 1 },
  33: { name: 'Pepsi', rarity: 1 },
  34: { name: 'Fanta Laranja', rarity: 1 },
  35: { name: 'Fanta Uva', rarity: 1 },
  36: { name: 'Guaraná', rarity: 1 },
  37: { name: 'Redbull', rarity: 1 },
  38: { name: 'Monster Energy', rarity: 1 },
  39: { name: 'Brahma', rarity: 1 },
  40: { name: 'Ziplock', rarity: 1 },
  41: { name: 'Maconha pura', rarity: 1 },
  42: { name: 'Maconha Embalada', rarity: 1 },
  43: { name: 'Cocaína pura', rarity: 1 },
  44: { name: 'Cocaína Embalada', rarity: 1 },
  45: { name: 'Kit de reparo', rarity: 1 },
  46: { name: 'Dinheiro Sujo', rarity: 1 },
  47: { name: 'Rádio Frequência', rarity: 1 },
  48: { name: 'Semente de Cocaína', rarity: 1 },
  49: { name: 'Semente de Maconha', rarity: 1 },
  50: { name: 'Celular', rarity: 1 },
  51: { name: 'Galão de Combustível', rarity: 1 },
  52: { name: 'Algema', rarity: 1 },
  53: { name: 'Identidade Civil', rarity: 1 },
  54: { name: 'Carteira de Motorista', rarity: 1 },
  55: { name: 'Explosivo C4', rarity: 1 },
  56: { name: 'Taser', rarity: 1 },
  57: { name: 'Binóculo', rarity: 1 },
  58: { name: 'Colete Balístico', rarity: 1 },
  59: { name: 'Adesivo Frontside Misty', rarity: 4 },
  60: { name: 'AK-47 Frontside Misty', rarity: 4 },
  61: { name: 'Terra Fértil', rarity: 1 },
  62: { name: 'Adesivo Hydroponic', rarity: 5 },
  63: { name: 'AK-47 Hydroponic', rarity: 5 },
  64: { name: 'Adesivo Aquamarine Revenge', rarity: 4 },
  65: { name: 'AK-47 Aquamarine Revenge', rarity: 4 },
  66: { name: 'Caixa Direct', rarity: 4 },
  67: { name: 'Caixa Direct Grátis', rarity: 2 },
  68: { name: 'Boné Gucci', rarity: 5 },
  69: { name: 'Boné Branco New York Yankees', rarity: 4 },
  70: { name: 'Boné Devil Vermelho', rarity: 4 },
  71: { name: 'Bandana Vermelha', rarity: 3 },
  72: { name: 'Câmera', rarity: 1 },
  73: { name: 'Gatilho', rarity: 1 },
  74: { name: 'Pente de Munição', rarity: 1 },
  75: { name: 'Retém do Ferrolho', rarity: 1 },
  76: { name: 'Corpo de Glock-18', rarity: 1 },
  77: { name: 'Projétil', rarity: 1 },
  78: { name: 'Estojo vazio (9mm)', rarity: 1 },
  79: { name: 'Pólvora', rarity: 1 },
  80: { name: 'G36c', rarity: 1 },
  81: { name: 'Tecido de Aramida', rarity: 1 },
  82: { name: 'Placa de aço', rarity: 1 },
  83: { name: 'Fita adesiva', rarity: 1 },
};

export function getItemName(id: number): string {
  return ITEMS[id]?.name ?? `Item #${id}`;
}

export function getItemRarity(id: number): number {
  return ITEMS[id]?.rarity ?? 1;
}
